# -*- coding: utf-8 -*-
"""Copy_of_Welcome_To_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/h399491-jpg/skillbit-technology/blob/main/Copy_of_Welcome_To_Colab.ipynb
"""

!pip install pandas numpy matplotlib seaborn scikit-learn



# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset
df = pd.read_csv('/content/kc_house_data.csv')

# Display First 5 Rows
print(df.head())

# Dataset Information
print(df.info())

# Check Missing Values
print(df.isnull().sum())

# Select Features
X = df[[
    'bedrooms',
    'bathrooms',
    'sqft_living',
    'sqft_lot',
    'floors',
    'waterfront',
    'view',
    'condition',
    'grade',
    'sqft_above',
    'sqft_basement',
    'yr_built',
    'yr_renovated',
    'zipcode',
    'lat',
    'long'
]]

# Target Variable
y = df['price']

# Split Dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Linear Regression Model
# -----------------------------

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train, y_train)

# Prediction
y_pred = lr.predict(X_test)

# Evaluation
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)

print("\n----- Linear Regression Results -----")
print("MAE :", mae)
print("MSE :", mse)
print("RMSE :", rmse)
print("R2 Score :", r2)

# Decision Tree Regressor
# -----------------------------

from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

dt_r2 = r2_score(y_test, dt_pred)

print("\n----- Decision Tree Results -----")
print("R2 Score :", dt_r2)

# Random Forest Regressor

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=42)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

rf_r2 = r2_score(y_test, rf_pred)

print("\n----- Random Forest Results -----")
print("R2 Score :", rf_r2)

# Visualization
# -----------------------------

plt.figure(figsize=(8,6))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")

plt.title("Actual vs Predicted House Prices")

plt.show()

# Correlation Heatmap
# -----------------------------

plt.figure(figsize=(12,10))

sns.heatmap(df.corr(numeric_only=True),
            cmap='coolwarm')

plt.title("Correlation Heatmap")

plt.show()

# Set your Git credentials
!git config --global user.email "h399491@gmail.com"
!git config --global user.name "h399491-jpg"

# Clone your repository
!git clone https://github.com/h399491-jpg/skillbit-technology.git